---
- name: Windows and MOVEit Detection steps
  hosts: MOVEit_Host_Group # The group of hosts you want to check
  tasks:
    - name: Fail if not a Windows server
      ansible.builtin.fail:
        msg: 'Not a Windows server'
      when: ansible_facts['os_family'] != 'Windows'

      # You can change the MOVEit_path variable if your installations are outside of the default path
    - name: Identify MOVEit software
      ansible.windows.win_stat:
        path: '{{ MOVEit_path | default("C:\Program Files\MOVEit\MiCentralCFG.exe") }}'
      register: installed

    - name: Fail if not a MOVEit server
      ansible.builtin.fail: 
        msg: 'Not a MOVEit server'
      when: installed.stat.exists != 'false'
