---
- name: MoveIT Response Test and Setup
  hosts: '{{moveit_servers|default("all")}}' # The group of hosts you want to remediate
  tasks:
    - name: Make sure MOVEit directory exists
      ansible.windows.win_file:
        path: C:\Program Files\MOVEit
        state: directory

    - name: Touch a MOVEit empty executable file
      ansible.windows.win_file:
        path: C:\Program Files\MOVEit\MiCentralCFG.exe
        state: touch

    - name: Touch a human2.aspx file
      ansible.windows.win_file:
        path: C:\Program Files\MOVEit\human2.aspx
        state: touch

    - name: Scan Filesystem
      ansible.windows.win_file:
        path: C:\
        recurse: true
      register: filesystem