---
# tasks file for moveit_server_scan
- name: Make sure chocolatey and yara are installed
  chocolatey.chocolatey.win_chocolatey:
    name: yara
    state: present

- name: Copy over the yara rules
  ansible.windows.win_copy:
    src: '{{ item }}'
    dest: C:\Temp\
  with_items:
    - ahmet_moveit.yar
    - mandiant_moveit.yar

- name: Get files in choco directory
  ansible.windows.win_find:
    recurse: true
    paths: 'C:\ProgramData\chocolatey\lib'

- name: Run the yara rules
  ansible.windows.win_command:
    cmd: 'C:\ProgramData\chocolatey\lib\yara\tools\yara64.exe ahmet_moveit.yar mandiant_moveit.yar C:\'
    chdir: C:\Temp
  register: yara_output
