---
# tasks file for moveit-server-check
- name: Fail if not a Windows host
  ansible.builtin.fail:
      msg: 'Not a Windows host'
  when: ansible_facts['os_family'] != 'Windows'

- name: Attempt to identify the MOVEit Executable
  ansible.windows.win_stat:
      path: '{{ moveit_server_check_path | default("C:\Program Files\MOVEit\MiCentralCFG.exe") }}'
  register: installed

- name: Fail if no MOVEit Executable is found
  ansible.builtin.fail:
      msg: 'MOVEit Executable not found in specifed path: {{ moveit_server_check_path | default("C:\Program Files\MOVEit\MiCentralCFG.exe") }}'
  when: installed.stat.exists is false

- name: MOVEit Server Identified
  ansible.builtin.debug:
      msg: 'Both a Windows host and a MOVEit executable have been found'
