---
# tasks file for moveit-server-check
- block:
    - name: Fail if not a Windows host
      ansible.builtin.fail:
        msg: 'Not a Windows host'
      when: ansible_facts['os_family'] != 'Windows'

      # You can change the MOVEit_path variable if your installations are outside of the default path
    - name: Attempt to identify the MOVEit Executable
      ansible.windows.win_stat:
        path: '{{ MOVEit_path | default("C:\Program Files\MOVEit\MiCentralCFG.exe") }}'
      register: installed
      failed_when: installed.stat.exists == 'false'

    - name: MOVEit Server Identified
      debug:
        msg: 'Both a Windows host and a MOVEit executable have been found'
- rescue:
    - name: Notify if Windows not detected
      debug:
        msg: 'This Operating System was not found to be Windows'
      when: ansible_facts['os_family'] != 'Windows'

    - name: Identify if the MOVEit Executable not detected
      debug:
        msg: 'The MOVEit Executable was not found to exist in the path defined in the MOVEit_path variable'
      when: installed.stat.exists == 'false'