---
# tasks file for moveit_server_scan_legacy
- name: Check for any instances of the human2.aspx (or any files with human2 prefix)
  ansible.windows.win_find:
    paths: '{{ scan_path }}'
    hidden: true
    recurse: true
    follow: true
    size: -1g
    patterns:
      - 'human2.*'
  register: first_scan

- name: Display matching human2 files
  ansible.builtin.debug:
    msg: '{{ item.path }}'
  with_items:
    - '{{ first_scan.files }}'

- name: Look for any new files created in the C:\MOVEitTransfer\wwwroot\ directory
  ansible.windows.win_find:
    paths: C:\MOVEitTransfer\wwwroot\
    hidden: true
    recurse: true
    follow: true
    age: -3w
  register: second_scan

- name: Display matching new files in wwwroot directory
  ansible.builtin.debug:
    msg: '{{ item.path }}'
  with_items:
    - '{{ second_scan.files }}'

- name: Look for new files created in the C:\Windows\TEMP\[random]\ directory with a file extension of [.]cmdline
  ansible.windows.win_find:
    paths: C:\Windows\TEMP\
    hidden: true
    recurse: true
    follow: true
    age: -10w
    patterns:
      - '*.cmdline'
  register: third_scan

- name: Display matching new cmdline files in TEMP
  ansible.builtin.debug:
    msg: '{{ item.path }}'
  with_items:
    - '{{ third_scan.files }}'

- name: Check all APP_WEB_[random].dll files located in C:\Windows\Microsoft. NET\Framework64\
  ansible.windows.win_find:
    paths: C:\Windows\Microsoft. NET\Framework64\
    hidden: true
    recurse: true
    follow: true
    patterns:
      - 'APP_WEB_*.dll'
  register: fourth_scan

- name: Display matching APP_WEB_*.dll files
  ansible.builtin.debug:
    msg: '{{ item.path }}'
  with_items:
    - '{{ fourth_scan.files }}'
