name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Execution Environment
      run: docker build . --file execution-environment/context/Containerfile --tag moveit_ee:$(date +%s)
